# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
pool:
  vmImage: macos-14

steps:

- task: UseNode@1
  displayName: Install Node
  inputs:
    version: '20.x'

- task: DownloadGitHubRelease@0
  displayName: Download aria-at-automation-driver $(aria_at_automation_driver_version)
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-github-release-v0?view=azure-pipelines
  inputs:
    connection: MyGitHubServiceConnection
    userRepository: w3c/aria-at-automation-driver
    defaultVersionType: specificTag
    version: v0.0.1-beta
    downloadPath: aria-at-automation-driver

- task: Bash@3
  displayName: Install automation-driver
  inputs:
    targetType: 'inline'
    workingDirectory: aria-at-automation-driver
    script: |
      tar zvxf *.tar.gz
      cd package
      npm install
      DEBUG=* ./bin/at-driver install --unattended

- task: Bash@3
  displayName: sleep for 3 minutes for testing purposes
  inputs:
    targetType: 'inline'
    script: sleep 180

- task: Bash@3
  displayName: say some stuff with custom voice
  inputs:
    targetType: 'inline'
    workingDirectory: aria-at-automation-driver/package/bin
    script: |
      set -x
      ./at-driver serve &
      sleep 3
      say "Hello world from say"
      sleep 1
      kill %%

- task: Bash@3
  displayName: say some stuff with custom voice (again)
  inputs:
    targetType: 'inline'
    workingDirectory: aria-at-automation-driver/package/bin
    script: |
      set -x
      ./at-driver serve &
      sleep 3
      say "Hello world from say"
      sleep 1
      kill %%

